Нужно больше функций
htmlacademy-univer-javascript-1/2506067-kekstagram-5 pull request #5
Opened 2024-09-22 12:38 UTC by 1DelFin1

---
:mortar_board: [Нужно больше функций](https://up.htmlacademy.ru/univer-js1/5/user/2506067/tasks/6)

2024-10-08 11:27 UTC, 1DelFin1 commented
переделал

2024-10-09 20:30 UTC, potyoma commented
> переделал

а запушил?  я не вижу изменений

2024-10-10 07:18 UTC, 1DelFin1 commented
Да, не знаю почему не выделяются изменения. И можете подсказать, что за ошибки появились?

2024-10-12 12:33 UTC, potyoma requested changes
если идёшь вперёд, создавай новые ветки. не надо  изменения новых домашек выкладывать в старой ветке. это будет сильно мешать при проверке. исправь ошибки после разбора - всё было озвучено. не надо игнорировать ошибки линтера. они вполне читаемы, внеси изменения в соответствии с ними

2024-10-12 13:06 UTC, 1DelFin1 commented
Хорошо, запомнил. Вроде все поправил

2024-10-15 10:16 UTC, merged